### ISSUE TITLE
Request repo name change to puppet-nashvillest

### ISSUE THREAD

**Issue by bval** [nashvillest/puppet-nashvillest#2]
Minor nitpick but can we name this repo to puppet-nashvillest? A repo named puppet easily gets lost in the noise, and it's not very friendly if you're cloning it to your own account to send PRs.

**Comment by bval** [comment]
Guessing if we do this it'll require manual intervention on the server since the cronjob is probably doing a git pull against this remote.

**Comment by cwage** [comment]
Done
